name:                art-generation
version:             0.1.0.0
github:              "githubuser/art-generation"
license:             BSD3
author:              "Nikita Aleschenko"
maintainer:          "n.aleschenko@innopolis.university"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/art-generation#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- random
- Rasterific
- mtl
- JuicyPixels-util
- conversion
- sort
- parallel
- deepseq
- deepseq-generics

library:
  source-dirs: src

executables:
  art-generation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6-qn1
    - -O2
    dependencies:
    - art-generation

tests:
  art-generation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - art-generation
